name: CI Workflow for Docker Build
on:
  push:
jobs:
  endproject:
    env:
     appName: "docker-image"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.appName }}:latest
      - name: Executing helm chart on Kubernetes Server Remotely
        uses: appleboy/ssh-action@v0.1.10
        with:
           host: 3.81.64.38
           username: root 
           password: root 
           port: 22 
           script: |
            git clone https://github.com/gbayru/Vodafone-DevOps-CapstoneProject.git
            cd Vodafone-DevOps-CapstoneProject
            helm list -A
            helm install mavenbuild-dev ./webapp
            helm list -A
            kubectl get all
